#!/bin/sh

#-------------------------------------------------------------------------------
# FATAL ERROR FUNCTION
#-------------------------------------------------------------------------------

RumiAI_fatal()
{
  [ -n "$1" ] && printf -- '%s\n' "$1" >&2

  exit 1
}

#-------------------------------------------------------------------------------
# CANONICALIZE EXISTING PATH FUNCTION
#-------------------------------------------------------------------------------

# RumiAI_path_canonicalize_existing <path>
# returns a canonicalized version of <path>, return error if does not exist
RumiAI_path_canonicalize_existing()
(
  if [ ! "$#" -eq 1 ] || [ ! -e "$1" ] || ! rp="$(command -p -- realpath -- "$1" 2>/dev/null)x"
  then
    return 1
  fi

  rp="${rp%x}"

  [ -e "$rp" ] || return 1
  printf -- '%s\n' "$rp"
)

m_readpathce_nnl()
{
  [ "$#" -eq 2 ] && [ -n "$1" ] && [ -n "$2" ] || return 1

  read -r "$1" <<EOF
$(
  set -eu
  shift
  # if invoked by PATH search, then acquire path used, safeguard against paths with trailing newline is automated by command -v
  case $1 in */*) cmd="$1";; *) cmd="$(command -v -- "$1" 2>/dev/null)";; esac
  [ -e "$cmd" ] || exit 1
  # resolve and canonicalize an existing path portably
  cmd="$(command -p -- realpath -- "$cmd" 2>/dev/null)"
  [ -e "$cmd" ] || exit 1
  printf -- '%s' "$cmd"
)
EOF

  # safeguard against invalid variable name: read will only fail when passing an invalid variable name
  [ "$?" = 0 ] || return 2
  # safeguard against failed subshell: read will pass with zero return code, but its varible will be empty and path empty is an error
  eval "[ -n \"\$$1\" ] || return 3"
}

m_readpathce_2()
{
  [ "$#" -eq 2 ] && [ -n "$1" ] && [ -n "$2" ] || return 1

  # safeguard against invalid variable name: read will make entire script fail when passing an invalid variable name
  case "$1" in "" | [0-9]* | *[!a-zA-Z0-9_]*) return 2 ;; esac

  read -r "$1" <<EOF
$(
  set -eu
  shift
  # if invoked by PATH search, then acquire path used, safeguard against paths with trailing newline (NB command -v always adds a newline)
  case $1 in */*) cmd="$1";; *) cmd="$(command -v -- "$1" 2>/dev/null; printf -- '%s' "x")"; cmd="${cmd%
x}";; esac
  [ -e "$cmd" ] || exit 1
  # resolve and canonicalize an existing path portably
  cmd="$(command -p -- realpath -- "$cmd" 2>/dev/null; printf -- '%s' "x")"
  cmd="${cmd%
x}"
  [ -e "$cmd" ] || exit 1
  printf -- '%s' "$cmd"
)
EOF

  # safeguard against failed subshell: read will pass with zero return code, but its varible will be empty and path empty is an error
  eval "[ -n \"\$$1\" ] || return 3"
}

m_readpathce()
{
  [ "$#" -eq 2 ] && [ -n "$1" ] && [ -n "$2" ] || return 1

  # safeguard against invalid variable name: read will make entire script fail when passing an invalid variable name
  case "$1" in "" | [0-9]* | *[!a-zA-Z0-9_]*) return 2 ;; esac

  set -- "$1" "$(
    set -eu
    shift
    # if invoked by PATH search, then acquire path used, safeguard against paths with trailing newline (NB command -v always adds a newline)
    case $1 in */*) cmd="$1";; *) cmd="$(command -v -- "$1" 2>/dev/null; printf -- '%s' "x")"; cmd="${cmd%
x}";; esac
    [ -e "$cmd" ] || exit 1
    # resolve and canonicalize an existing path portably
    cmd="$(command -p -- realpath -- "$cmd" 2>/dev/null; printf -- '%s' "x")"
    cmd="${cmd%
x}"
    [ -e "$cmd" ] || exit 1
    printf -- '%s' "${cmd}x"
)"

  set -- "$1" "${2%
x}"

  # safeguard against failed subshell: read will pass with zero return code, but its varible will be empty and path empty is an error
  [ -n "$2" ] || return 3

  eval $1='$2'
}

#-------------------------------------------------------------------------------
# ROOT RESOLUTION
#-------------------------------------------------------------------------------

# canonicalize the path of this script and check that it is really a file
m_readpathce "RumiAI_BOOTSTRAP_BIN" "$0" && [ -f "$RumiAI_BOOTSTRAP_BIN" ] || RumiAI_fatal 'RumiAI_BOOTSTRAP_BIN_RESOLUTION_ERROR'

# extract root
RumiAI_ROOT=${RumiAI_BOOTSTRAP_BIN%/*}
[ -n "$RumiAI_ROOT" ] || RumiAI_ROOT=/

# check can cd into it
(cd -- "$RumiAI_ROOT" 2>/dev/null) || RumiAI_fatal 'RumiAI_BOOTSTRAP_FATAL_ROOT_ERROR'

# export root
export -- RumiAI_BOOTSTRAP_BIN RumiAI_ROOT

readonly -- RumiAI_BOOTSTRAP_BIN RumiAI_ROOT

#-------------------------------------------------------------------------------
# FUNDAMENTAL SYSTEM DIRECTORIES
#-------------------------------------------------------------------------------

# set values
RumiAI_BIN_DIR=$RumiAI_ROOT/bin
RumiAI_BIN_SYS_DIR=$RumiAI_BIN_DIR/@sys
RumiAI_LIB_DIR=$RumiAI_ROOT/lib
RumiAI_CONF_DIR=$RumiAI_ROOT/conf
RumiAI_LANG_DIR=$RumiAI_ROOT/lang

# export vars
export -- \
  RumiAI_BIN_DIR \
  RumiAI_BIN_SYS_DIR \
  RumiAI_LIB_DIR \
  RumiAI_CONF_DIR \
  RumiAI_LANG_DIR

readonly -- \
  RumiAI_BIN_DIR \
  RumiAI_BIN_SYS_DIR \
  RumiAI_LIB_DIR \
  RumiAI_CONF_DIR \
  RumiAI_LANG_DIR

#-------------------------------------------------------------------------------
# TEXT
#-------------------------------------------------------------------------------

# functions
RumiAI_is_integer()
{
  [ "$#" -eq 1 ] || return 1

  case "$1" in *[!0-9]* | "") return 2;; *) return 0;; esac
}

RumiAI_text_safe_id()
{
  [ "$#" -eq 1 ] || return 1

  case "$1" in
    # first character match
    [a-z0-9]*)
      # middle characters and final character exclusions
      case $1 in
        *[!a-z0-9._-]* | *[._-])
          return 1
          ;;
      esac
      ;;
    *)
      return 1
      ;;
  esac

  return 0
}

RumiAI_text_safe_id_case()
{
  [ "$#" -eq 1 ] || return 1

  case "$1" in
    # first character match
    [A-Za-z0-9]*)
      # middle characters and final character exclusions
      case $1 in
        *[!A-Za-z0-9._-]* | *[._-])
          return 1
          ;;
      esac
      ;;
    *)
      return 1
      ;;
  esac

  return 0
}

#-------------------------------------------------------------------------------
# LANG
#-------------------------------------------------------------------------------

# functions
lang()
(
  [ "$#" -eq 2 ] || return 1

  RumiAI_lang_domain=$1
  RumiAI_lang_message_id=$2

  RumiAI_text_safe_id "$RumiAI_lang_domain" && RumiAI_text_safe_id "$RumiAI_lang_message_id" || return 2

  RumiAI_lang_message="$(command -p -- cat "$RumiAI_LANG_DIR/@current/$RumiAI_lang_domain/$RumiAI_lang_message_id" 2>/dev/null)"
  if [ "$?" != 0 ]
  then
    case "$RumiAI_LANGUAGE_FALLBACK" in [a-z][a-z]_[A-Z][A-Z]) true;; *) false;; esac && RumiAI_lang_message="$(command -p -- cat "$RumiAI_LANG_DIR/$RumiAI_LANGUAGE_FALLBACK/$RumiAI_lang_domain/$RumiAI_lang_message_id" 2>/dev/null)"
    if [ "$?" != 0 ]
    then
      RumiAI_lang_message="${RumiAI_lang_domain}.${RumiAI_lang_message_id}"
    fi
  fi

  printf -- '%s\n' "$RumiAI_lang_message"
)

# set var - language
RumiAI_LANGUAGE_FALLBACK=en_US

# set var - text encoding
RumiAI_TEXT_ENCODING=UTF-8

# export variables
export -- \
  RumiAI_LANGUAGE_FALLBACK \
  RumiAI_TEXT_ENCODING

#-------------------------------------------------------------------------------
# LOGGER
#-------------------------------------------------------------------------------

: "${RumiAI_LOG_LEVEL:=info}"

RumiAI_log_fields_valid()
(
  [ "$(( $# % 2 ))" -eq 0 ] || return 1

  while [ "$#" -gt 0 ]
  do
    RumiAI_text_safe_id "$1" || return 1
    shift 2
  done

  return 0
)

log()
(
  [ "$#" -ge 3 ] || return 1

  RumiAI_log_severity="$1"
  shift

  case "$RumiAI_log_severity" in
    fatal)
      RumiAI_log_priority=1
      ;;
    error)
      RumiAI_log_priority=2
      ;;
    warn)
      RumiAI_log_priority=3
      ;;
    info)
      RumiAI_log_priority=4
      ;;
    debug)
      RumiAI_log_priority=5
      ;;
    trace)
      RumiAI_log_priority=6
      ;;
    *)
      return 2
      ;;
  esac

  case "$RumiAI_LOG_LEVEL" in
    off | none)
      RumiAI_log_threshold="0"
      ;;
    fatal)
      RumiAI_log_threshold="1"
      ;;
    error)
      RumiAI_log_threshold="2"
      ;;
    warn)
      RumiAI_log_threshold="3"
      ;;
    info)
      RumiAI_log_threshold="4"
      ;;
    debug)
      RumiAI_log_threshold="5"
      ;;
    trace | all)
      RumiAI_log_threshold="6"
      ;;
    *)
      return 6
      ;;
  esac

  [ "$RumiAI_log_priority" -le "$RumiAI_log_threshold" ] || return 0

  RumiAI_log_domain=$1
  RumiAI_log_message_id=$2
  shift 2

  RumiAI_text_safe_id "$RumiAI_log_domain" || \
    return 3

  RumiAI_text_safe_id "$RumiAI_log_message_id" || \
    return 4

  RumiAI_log_fields_valid "$@" || return 5

  if ! RumiAI_log_message=$(lang "$RumiAI_log_domain" "$RumiAI_log_message_id")
  then
    RumiAI_log_message=$RumiAI_log_domain.$RumiAI_log_message_id
  fi

  if ! RumiAI_log_timestamp=$(command -p -- date '+%Y-%m-%dT%H:%M:%S' 2>/dev/null)
  then
    RumiAI_log_timestamp=-
  fi

  printf -- '[%s] [%s] [%s.%s] %s' \
    "$RumiAI_log_timestamp" \
    "$RumiAI_log_severity" \
    "$RumiAI_log_domain" \
    "$RumiAI_log_message_id" \
    "$RumiAI_log_message" >&2

  while [ "$#" -gt 0 ]
  do
    RumiAI_log_field_name=$1
    RumiAI_log_field_value=$2
    shift 2

    printf -- ' [%s="%s"]' \
      "$RumiAI_log_field_name" \
      "$RumiAI_log_field_value" >&2
  done

  printf -- '\n' >&2
)

#-------------------------------------------------------------------------------
# OSARCH DETECTION
#-------------------------------------------------------------------------------

RumiAI_OSARCH_OS=$(command -p uname -s 2>/dev/null) || RumiAI_fatal 'RumiAI_BOOTSTRAP_FATAL_OSARCH_ERROR'

# normalize known operative systems, leave intact others
case $RumiAI_OSARCH_OS in
  Linux)
    RumiAI_OSARCH_OS="linux"
    ;;
  Darwin)
    RumiAI_OSARCH_OS="macos"
    ;;
  MINGW*|MSYS*|CYGWIN*)
    RumiAI_OSARCH_OS="windows"
    ;;
esac

RumiAI_OSARCH_ARCH=$(command -p uname -m 2>/dev/null) || RumiAI_fatal 'RumiAI_BOOTSTRAP_FATAL_OSARCH_ERROR'

# normalize known architectures, leave intact others
case $RumiAI_OSARCH_ARCH in
  arm64|aarch64)
    RumiAI_OSARCH_ARCH="arm64"
    ;;
  x86_64|amd64|AMD64)
    RumiAI_OSARCH_ARCH="x86_64"
    ;;
esac

RumiAI_OSARCH=$RumiAI_OSARCH_OS-$RumiAI_OSARCH_ARCH
RumiAI_OSARCH_BIN_DIR=$RumiAI_BIN_DIR/@osarch/$RumiAI_OSARCH
RumiAI_OSARCH_BIN_SYS_DIR=$RumiAI_OSARCH_BIN_DIR/@sys

PATH=$RumiAI_OSARCH_BIN_SYS_DIR:$RumiAI_OSARCH_BIN_DIR:$RumiAI_BIN_SYS_DIR:$RumiAI_BIN_DIR${PATH:+:$PATH}

export -- \
  RumiAI_OSARCH_OS \
  RumiAI_OSARCH_ARCH \
  RumiAI_OSARCH \
  RumiAI_OSARCH_BIN_DIR \
  PATH

readonly -- \
  RumiAI_OSARCH_OS \
  RumiAI_OSARCH_ARCH \
  RumiAI_OSARCH \
  RumiAI_OSARCH_BIN_DIR

#-------------------------------------------------------------------------------
# EXECUTE
#-------------------------------------------------------------------------------

# execute shell
if [ "$#" -eq 0 ]
then
  : "${SHELL:=sh}"
  printf -- '%s\n'  "$(tput setaf 2)$(tput bold)${SHELL} $(tput setaf 7)RumiAI$(tput sgr0)" >&2
  exec "${SHELL}"
fi

# execute command
if ! RumiAI_COMMAND_BIN=$(RumiAI_path_canonicalize_existing "$1")
then
  log fatal filesystem path-resolution-failed path "$1"
  exit 1
fi
shift

if [ ! -f "$RumiAI_COMMAND_BIN" ] || [ ! -r "$RumiAI_COMMAND_BIN" ] || [ "$RumiAI_COMMAND_BIN" = "$RumiAI_BOOTSTRAP_BIN" ]
then
  log fatal filesystem path-invalid command-invalid "$RumiAI_COMMAND_BIN"
  exit 1
fi

# export variables
export -- RumiAI_COMMAND_BIN

readonly -- RumiAI_COMMAND_BIN

# execute command
. "$RumiAI_COMMAND_BIN"
exit $?
