
#------------------------------------------------------------------------------

# encodes stdin to stdout using GNU GnuPG symmetric OCB encryption
#
# Requires GNU gpg in PATH with support for --use-ocb-sym.
# If gpg is unavailable or does not support --use-ocb-sym, returns 1
# before consuming stdin or asking for a password.
#
# ENC_PASS may provide the passphrase. If ENC_PASS is unset or empty,
# the passphrase is read twice from /dev/tty using _enc_password_read().
#
# Encryption uses:
#
#   AES-256
#   OCB authenticated encryption
#   64 KiB OCB chunks
#   iterated-and-salted S2K
#   SHA-256 for S2K
#   S2K count 65011712
#   no compression
#
# The output is the binary OpenPGP stream produced directly by gpg.
# No temporary files or in-memory ciphertext buffering are used.
#
# The passphrase is supplied through a dedicated file descriptor and
# does not appear in the gpg command line or environment.
#
# Passphrases containing newline characters are rejected because
# --passphrase-fd reads only the first line.
#
# Returns:
#
#   0  success
#   1  gpg unavailable/unsupported or encryption/runtime error
#   2  invalid function arguments

encode()
(
  set +x

  [ "$#" -eq "0" ] || return 2

  command -v gpg >/dev/null 2>&1 || return 1

  gpg --no-options --dump-options 2>/dev/null |
    grep -qx -e '--use-ocb-sym' ||
    return 1

  if [ "${ENC_PASS+x}" != "x" ] || [ -z "$ENC_PASS" ]
  then
    ENC_PASS="$(_enc_password_read "Encryption password: ")" || return 1
    [ -n "$ENC_PASS" ] || return 1

    _enc_password_confirm="$(
      _enc_password_read "Verify encryption password: "
    )" || return 1

    [ "$ENC_PASS" = "$_enc_password_confirm" ] || return 1

    unset _enc_password_confirm
  fi

  _enc_password="$ENC_PASS"
  unset ENC_PASS

  _enc_nl='
'

  [ "${_enc_password%%"$_enc_nl"*}" = "$_enc_password" ] ||
    return 1

  exec 3<&0 || return 1

  printf '%s\n' "$_enc_password" |
    gpg \
      --no-options \
      --batch \
      --no-tty \
      --quiet \
      --pinentry-mode loopback \
      --passphrase-fd 4 \
      --no-symkey-cache \
      --gnupg \
      --cipher-algo AES256 \
      --s2k-mode 3 \
      --s2k-digest-algo SHA256 \
      --s2k-count 65011712 \
      --no-compress \
      --chunk-size 16 \
      --use-ocb-sym \
      --output - \
      --symmetric \
      4<&0 0<&3 3<&- ||
    return 1
}

#------------------------------------------------------------------------------

# decodes an OpenPGP encrypted stream from stdin to stdout using GNU GnuPG
#
# Requires GNU gpg in PATH. OCB messages generated by encode() require
# GnuPG with OCB decryption support.
#
# ENC_PASS may provide the passphrase. If ENC_PASS is unset or empty,
# the passphrase is read from /dev/tty using _enc_password_read().
#
# Decryption is intentionally streaming and best-effort.
#
# Plaintext produced by gpg is written immediately to stdout. If corruption
# or authentication failure is discovered later in the stream, decode returns
# 1 but DOES NOT retract or discard plaintext already emitted.
#
# Therefore the contract is:
#
#   exit status 0
#       the complete stream was successfully decrypted and authenticated
#
#   exit status 1
#       decryption/authentication failed; stdout may already contain partial
#       plaintext and, depending on where the failure was detected, data from
#       the damaged portion of the stream
#
# A caller that requires all-or-nothing authenticated plaintext must therefore
# buffer decode's output externally and use it only after a zero exit status.
# Callers interested in best-effort recovery may instead consume the streamed
# output even when the final status is non-zero.
#
# No temporary files or ciphertext buffering are used.
#
# The passphrase is supplied through a dedicated file descriptor and
# does not appear in the gpg command line or environment.
#
# Passphrases containing newline characters are rejected because
# --passphrase-fd reads only the first line.
#
# Returns:
#
#   0  complete successful authenticated decryption
#   1  gpg unavailable or decryption/authentication/runtime error
#   2  invalid function arguments

decode()
(
  set +x

  [ "$#" -eq "0" ] || return 2

  command -v gpg >/dev/null 2>&1 || return 1

  if [ "${ENC_PASS+x}" != "x" ] || [ -z "$ENC_PASS" ]
  then
    ENC_PASS="$(_enc_password_read "Decryption password: ")" || return 1
    [ -n "$ENC_PASS" ] || return 1
  fi

  _enc_password="$ENC_PASS"
  unset ENC_PASS

  _enc_nl='
'

  [ "${_enc_password%%"$_enc_nl"*}" = "$_enc_password" ] ||
    return 1

  exec 3<&0 || return 1

  printf '%s\n' "$_enc_password" |
    gpg \
      --no-options \
      --batch \
      --no-tty \
      --quiet \
      --pinentry-mode loopback \
      --passphrase-fd 4 \
      --no-symkey-cache \
      --gnupg \
      --output - \
      --decrypt \
      4<&0 0<&3 3<&- ||
    return 1
}

#------------------------------------------------------------------------------

# decodes file sourcing (executing) it into current shell script

encoded_file_import()
{
  if [ ! -f "$1" ]
  then
    set -- "$(command -v "$1")"

    if [ "$?" != "0" ] || [ ! -f "$1" ]
    then
      return 1
    fi
  fi

  eval "$(decode < "$1")"
}

#------------------------------------------------------------------------------

# sets the editor command

encoded_file_editor()
{
  if ! command -v "$1"
  then
    return 1
  fi

  export ENCODED_FILE_EDITOR="$1"
}

#------------------------------------------------------------------------------

# decodes file, opens it in editor, re-encodes it streaming into original

encoded_file_edit()
{
  if [ ! -f "$1" ]
  then
    set -- "$(command -v "$1")"

    if [ "$?" != "0" ] || [ ! -f "$1" ]
    then
      return 1
    fi
  fi

  (
    if [ -z "$ENCODED_FILE_EDITOR" ]
    then
      ENCODED_FILE_EDITOR="nano"
    fi

    # DECODED_FILE="${1}.$(date +"[%Y-%m-%d %H:%M:%S]").dec" && \
    # decode < "$1" > "$DECODED_FILE" && \
    # "$ENCODED_FILE_EDITOR" "$DECODED_FILE" && \
    # encode < "$DECODED_FILE" > "$1"

    DECODED_FILE="${1}.$(date +"[%Y-%m-%d %H:%M:%S]").dec" && \
    decode < "$1" > "$DECODED_FILE" && \
    "$ENCODED_FILE_EDITOR" "$DECODED_FILE"

    echo "reencode file: $1? YES, NO (default = YES): " >&2
    read REENCODE_CHOICE
    if [ "$REENCODE_CHOICE" = "YES" ] || [ "$REENCODE_CHOICE" = "yes" ] || [ "$REENCODE_CHOICE" = "Y" ] || [ "$REENCODE_CHOICE" = "y" ] || [ "$REENCODE_CHOICE" = "Yes" ]
    then
      encode < "$DECODED_FILE" > "$1"
    fi

    rm -f "$DECODED_FILE"
  )
}

#------------------------------------------------------------------------------

# converts bytes to whitespace-separated 3-digit octal octets
# with no arguments reads stdin, otherwise encodes the concatenated arguments

a2o()
{
  if [ "$#" -eq "0" ]
  then
    od -v -A n -t o1
  else
    printf '%s' "$@" | od -v -A n -t o1
  fi
}

# converts whitespace-separated octal octets to bytes
# with no arguments reads stdin; accepted octets are 0..377

o2a()
{
  (
    set -f
    IFS=' 	
'

    if [ "$#" -eq "0" ]
    then
      _o2a_input="$(cat)" || return 1
    else
      _o2a_input="$*"
    fi

    set -- $_o2a_input

    for _o2a_octet
    do
      _o2a_length="${#_o2a_octet}"

      if [ "$_o2a_length" -lt "1" ] || [ "$_o2a_length" -gt "3" ]
      then
        return 1
      fi

      [ "$_o2a_octet" = "${_o2a_octet%%[!01234567]*}" ] || return 1

      if [ "$_o2a_length" -eq "3" ]
      then
        _o2a_first="${_o2a_octet%??}"

        if [ "$_o2a_first" != "0" ] &&
           [ "$_o2a_first" != "1" ] &&
           [ "$_o2a_first" != "2" ] &&
           [ "$_o2a_first" != "3" ]
        then
          return 1
        fi
      fi
    done

    for _o2a_octet
    do
      printf '%b' "\\0$_o2a_octet" || return 1
    done
  )
}

#-------------------------------------------------------------------------------
