
#------------------------------------------------------------------------------

# encodes stdin to stdout using GNU GnuPG symmetric OCB encryption
#
# Requires GNU gpg in PATH with symmetric OCB encryption support.
# encode() prefers --use-ocb-sym and falls back to --force-ocb when the
# installed gpg advertises only the older option. If neither option is
# available, returns 1 before consuming stdin or asking for a passphrase.
#
# m_ENC_PASS may provide the passphrase as a shell variable. It should not be
# exported. If non-empty, encode() copies it into subshell positional state,
# unsets m_ENC_PASS before executing any external command, and supplies the
# passphrase to gpg only through file descriptor 3.
#
# If m_ENC_PASS is unset or empty, GnuPG/Pinentry acquires the passphrase
# interactively. Encryption requests one passphrase repetition for
# confirmation.
#
# Encryption uses:
#
#   AES-256
#   OCB authenticated encryption
#   64 KiB OCB chunks
#   iterated-and-salted S2K
#   SHA-256 for S2K
#   S2K count 65011712
#   no compression
#
# The output is the binary OpenPGP stream produced directly by gpg.
# No temporary files or in-memory ciphertext buffering are used.
#
# Supplied passphrases containing newline characters are rejected because
# --passphrase-fd reads only the first line.
#
# Encryption is streaming. If gpg fails after writing output, stdout may
# already contain a partial OpenPGP stream. Callers replacing durable
# ciphertext must therefore commit the output only after a zero exit status.
#
# Returns:
#
#   0  success
#   1  gpg unavailable/unsupported or encryption/runtime error
#   2  invalid function arguments

encode()
(
  set +x

  [ "$#" -eq "0" ] || return 2

  if [ -n "${m_ENC_PASS-}" ]
  then
    set -- "$m_ENC_PASS"
  else
    set -- ''
  fi
  unset m_ENC_PASS

  case "$1" in
    *'
'*) return 1 ;;
  esac

  unset _enc_gpg_options
  _enc_gpg_options="$(command gpg --no-options --dump-options 2>/dev/null)" ||
    return 1

  if printf '%s\n' "$_enc_gpg_options" |
     command grep -qx -e '--use-ocb-sym'
  then
    set -- "$1" '--use-ocb-sym'
  elif printf '%s\n' "$_enc_gpg_options" |
       command grep -qx -e '--force-ocb'
  then
    set -- "$1" '--force-ocb'
  else
    return 1
  fi

  unset _enc_gpg_options

  if [ -n "$1" ]
  then
    command gpg \
      --no-options \
      --batch \
      --no-tty \
      --quiet \
      --pinentry-mode loopback \
      --passphrase-fd 3 \
      --no-symkey-cache \
      --gnupg \
      --cipher-algo AES256 \
      --s2k-mode 3 \
      --s2k-digest-algo SHA256 \
      --s2k-count 65011712 \
      --no-compress \
      --chunk-size 16 \
      "$2" \
      --output - \
      --symmetric \
      3<<EOF_PASS ||
        return 1
$1
EOF_PASS
  else
    command gpg \
      --no-options \
      --no-tty \
      --quiet \
      --no-symkey-cache \
      --gnupg \
      --passphrase-repeat 1 \
      --cipher-algo AES256 \
      --s2k-mode 3 \
      --s2k-digest-algo SHA256 \
      --s2k-count 65011712 \
      --no-compress \
      --chunk-size 16 \
      "$2" \
      --output - \
      --symmetric ||
        return 1
  fi
)

#------------------------------------------------------------------------------

# decodes an OpenPGP encrypted stream from stdin to stdout using GNU GnuPG
#
# Requires GNU gpg in PATH. OCB messages generated by encode() require
# GnuPG with OCB decryption support.
#
# m_ENC_PASS may provide the passphrase as a shell variable. It should not be
# exported. If non-empty, decode() copies it into subshell positional state,
# unsets m_ENC_PASS before executing gpg, and supplies the passphrase only
# through file descriptor 3.
#
# If m_ENC_PASS is unset or empty, GnuPG/Pinentry acquires the passphrase
# interactively.
#
# Decryption is intentionally streaming and best-effort.
#
# Plaintext produced by gpg is written immediately to stdout. If corruption
# or authentication failure is discovered later in the stream, decode returns
# 1 but DOES NOT retract or discard plaintext already emitted.
#
# Therefore the contract is:
#
#   exit status 0
#       the complete stream was successfully decrypted and authenticated
#
#   exit status 1
#       decryption/authentication failed; stdout may already contain partial
#       plaintext and, depending on where the failure was detected, data from
#       the damaged portion of the stream
#
# A caller that requires all-or-nothing authenticated plaintext must therefore
# buffer decode's output externally and use it only after a zero exit status.
# Callers interested in best-effort recovery may instead consume the streamed
# output even when the final status is non-zero.
#
# No temporary files or ciphertext buffering are used.
#
# Supplied passphrases containing newline characters are rejected because
# --passphrase-fd reads only the first line.
#
# Returns:
#
#   0  complete successful authenticated decryption
#   1  gpg unavailable or decryption/authentication/runtime error
#   2  invalid function arguments

decode()
(
  set +x

  [ "$#" -eq "0" ] || return 2

  if [ -n "${m_ENC_PASS-}" ]
  then
    set -- "$m_ENC_PASS"
  else
    set -- ''
  fi
  unset m_ENC_PASS

  case "$1" in
    *'
'*) return 1 ;;
  esac

  if [ -n "$1" ]
  then
    command gpg \
      --no-options \
      --batch \
      --no-tty \
      --quiet \
      --pinentry-mode loopback \
      --passphrase-fd 3 \
      --no-symkey-cache \
      --gnupg \
      --output - \
      --decrypt \
      3<<EOF_PASS ||
        return 1
$1
EOF_PASS
  else
    command gpg \
      --no-options \
      --no-tty \
      --quiet \
      --no-symkey-cache \
      --gnupg \
      --output - \
      --decrypt ||
        return 1
  fi
)

#------------------------------------------------------------------------------

encoded_file_eval()
{
  [ "$#" -gt "0" ] && [ -n "$1" ] || return 1

  case "$-" in
    *x*) set +x; set -- "set -x" "$@";;
    *) set -- ":" "$@";;
  esac

  eval "$(
    if pathsearch _encoded_file_eval_file "$2"
    then
      _encoded_file_eval_source="$(decode < "$_encoded_file_eval_file")" || _encoded_file_eval_source="return 3"
    else
      _encoded_file_eval_source="return 2"
    fi
    command -p -- cat << EOF
shift 2
$1
$_encoded_file_eval_source
EOF
  )"
}

#------------------------------------------------------------------------------

# decodes encrypted files, edits plaintext in memory with vsed, and
# replaces each original only after the complete pipeline succeeds
#
# Usage:
#
#   encoded_file_edit [--preserve-timestamp] [--] file...
#
# cp -p seeds the temporary ciphertext with the original ownership and mode,
# including executable bits. Preservation therefore fails when the caller
# lacks the privileges required to reproduce those metadata.
#
# By default the rewritten file receives the modification time of the new
# ciphertext. --preserve-timestamp restores the target's current mtime before
# replacement. ctime is not preserved.
#
# Returns 0 when every file is committed and non-zero on invalid invocation,
# cancellation or any resolution, pipeline, metadata, concurrency or commit
# failure.
encoded_file_edit()
(
  set +x
  set -o pipefail || return 1

  _encoded_file_edit_preserve_timestamp=0

  while [ "$#" -gt "0" ]
  do
    case "$1" in
      --preserve-timestamp)
        _encoded_file_edit_preserve_timestamp=1
        shift
        ;;
      --)
        shift
        break
        ;;
      -*)
        return 1
        ;;
      *)
        break
        ;;
    esac
  done

  [ "$#" -gt "0" ] || return 1

  umask 077
  _encoded_file_edit_tmp=

  trap '[ -z "$_encoded_file_edit_tmp" ] || command -p rm -f -- "$_encoded_file_edit_tmp"' 0
  trap 'exit 129' HUP
  trap 'exit 130' INT
  trap 'exit 131' QUIT
  trap 'exit 143' TERM

  for _encoded_file_edit_operand
  do
    pathsearch _encoded_file_edit_file "$_encoded_file_edit_operand" ||
      return 1

    _encoded_file_edit_checksum="$(
      command -p cksum < "$_encoded_file_edit_file"
    )" || return 1

    _encoded_file_edit_candidate="$_encoded_file_edit_file.$$"

    set -C
    : > "$_encoded_file_edit_candidate" || return 1
    set +C

    _encoded_file_edit_tmp=$_encoded_file_edit_candidate

    command -p cp -p -- \
      "$_encoded_file_edit_file" \
      "$_encoded_file_edit_tmp" ||
        return 1

    decode < "$_encoded_file_edit_file" |
      command -- vsed |
      encode > "$_encoded_file_edit_tmp" ||
        return 1

    [ "$_encoded_file_edit_checksum" = "$(
      command -p cksum < "$_encoded_file_edit_file"
    )" ] ||
      return 1

    if [ "$_encoded_file_edit_preserve_timestamp" -eq "1" ]
    then
      command -p touch -m -r \
        "$_encoded_file_edit_file" \
        "$_encoded_file_edit_tmp" ||
          return 1
    fi

    command -p mv -f -- \
      "$_encoded_file_edit_tmp" \
      "$_encoded_file_edit_file" ||
        return 1

    _encoded_file_edit_tmp=
  done
)

#------------------------------------------------------------------------------

# converts bytes to whitespace-separated 3-digit octal octets
# with no arguments reads stdin, otherwise encodes the concatenated arguments

a2o()
{
  if [ "$#" -eq "0" ]
  then
    od -v -A n -t o1
  else
    printf '%s' "$@" | od -v -A n -t o1
  fi
}

# converts whitespace-separated octal octets to bytes
# with no arguments reads stdin; accepted octets are 0..377

o2a()
{
  (
    set -f
    IFS='
'

    if [ "$#" -eq "0" ]
    then
      _o2a_input="$(cat)" || return 1
    else
      _o2a_input="$*"
    fi

    set -- $_o2a_input

    for _o2a_octet
    do
      _o2a_length="${#_o2a_octet}"

      if [ "$_o2a_length" -lt "1" ] || [ "$_o2a_length" -gt "3" ]
      then
        return 1
      fi

      [ "$_o2a_octet" = "${_o2a_octet%%[!01234567]*}" ] || return 1

      if [ "$_o2a_length" -eq "3" ]
      then
        _o2a_first="${_o2a_octet%??}"

        if [ "$_o2a_first" != "0" ] &&
           [ "$_o2a_first" != "1" ] &&
           [ "$_o2a_first" != "2" ] &&
           [ "$_o2a_first" != "3" ]
        then
          return 1
        fi
      fi
    done

    for _o2a_octet
    do
      printf '%b' "\\0$_o2a_octet" || return 1
    done
  )
}

#-------------------------------------------------------------------------------
